### ISSUE TITLE
Example Native UI Swift

### ISSUE THREAD

**Issue by sibelius** [ModusCreateOrg/swift-modules-for-react-native#1]
Do you have an example of how to bridge an UI from Swift?

**Comment by indu127pal** [comment]
+1

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
